import type { ThemeConfig } from "antd";
import { theme } from "antd";
import { tokens } from "./tokens";

export function buildAntdTheme(): ThemeConfig {
  return {
    algorithm: theme.defaultAlgorithm,
    cssVar: true,
    hashed: false,
    token: {
      colorPrimary: tokens.accent,
      colorInfo: tokens.accent,
      colorSuccess: tokens.success,
      colorWarning: tokens.warning,
      colorError: tokens.critical,
      colorBgBase: tokens.bg,
      colorBgContainer: tokens.surface,
      colorBgElevated: tokens.surfaceElevated,
      colorBgLayout: tokens.bg,
      colorText: tokens.text,
      colorTextSecondary: tokens.textSecondary,
      colorTextTertiary: tokens.textTertiary,
      colorBorder: tokens.border,
      colorBorderSecondary: tokens.separator,
      borderRadius: tokens.radius.md,
      borderRadiusLG: tokens.radius.lg,
      borderRadiusSM: tokens.radius.sm,
      borderRadiusXS: tokens.radius.xs,
      fontFamily: tokens.font.family,
      fontFamilyCode: tokens.font.mono,
      fontSize: 14,
      sizeStep: 4,
      sizeUnit: 4,
      motionDurationFast: `${tokens.duration.fast}ms`,
      motionDurationMid: `${tokens.duration.base}ms`,
      motionDurationSlow: `${tokens.duration.slow}ms`,
      motionEaseInOut: tokens.ease.standard,
      motionEaseOut: tokens.ease.spring,
      boxShadow: tokens.shadow.sm,
      boxShadowSecondary: tokens.shadow.md,
      boxShadowTertiary: tokens.shadow.lg,
      wireframe: false,
    },
    components: {
      Layout: {
        bodyBg: tokens.bg,
        headerBg: "transparent",
        siderBg: "transparent",
        headerHeight: 56,
        headerPadding: "0 24px",
      },
      Menu: {
        itemBg: "transparent",
        itemSelectedBg: "rgba(0,113,227,0.10)",
        itemHoverBg: "rgba(0,0,0,0.04)",
        itemSelectedColor: tokens.accent,
        itemBorderRadius: tokens.radius.sm,
        itemMarginInline: 8,
        itemMarginBlock: 2,
        iconSize: 16,
        collapsedIconSize: 18,
      },
      Card: {
        borderRadiusLG: tokens.radius.lg,
        paddingLG: 20,
        boxShadowTertiary: tokens.shadow.sm,
      },
      Button: {
        borderRadius: tokens.radius.sm,
        controlHeight: 36,
        fontWeight: 500,
        primaryShadow: "none",
        defaultShadow: "none",
      },
      Table: {
        borderRadius: tokens.radius.lg,
        headerBg: "transparent",
        headerColor: tokens.textSecondary,
        headerSplitColor: "transparent",
        rowHoverBg: "rgba(0,0,0,0.025)",
        cellPaddingBlock: 14,
        cellPaddingInline: 16,
        fontSize: 13,
      },
      Input: {
        borderRadius: tokens.radius.sm,
        controlHeight: 36,
        activeBorderColor: tokens.accent,
        hoverBorderColor: tokens.accent,
      },
      Select: {
        borderRadius: tokens.radius.sm,
        controlHeight: 36,
        optionSelectedBg: "rgba(0,113,227,0.10)",
      },
      Modal: {
        borderRadiusLG: tokens.radius.xl,
        paddingLG: 28,
        titleFontSize: 17,
      },
      Tag: {
        borderRadiusSM: 6,
        defaultBg: "rgba(0,0,0,0.05)",
        defaultColor: tokens.textSecondary,
      },
      Statistic: {
        contentFontSize: 28,
        titleFontSize: 13,
      },
      Form: {
        verticalLabelPadding: "0 0 8px",
        labelFontSize: 13,
      },
      Tabs: {
        cardBg: "transparent",
        itemSelectedColor: tokens.accent,
        inkBarColor: tokens.accent,
      },
      Notification: {
        borderRadiusLG: tokens.radius.lg,
      },
    },
  };
}
